### ISSUE TITLE
direct output to system clip-board buffer?

### ISSUE THREAD

**Issue by heapwolf** [hij1nx/pxx#1]
maybe instead of printing the unencrypted text to stdout it would be cool to direct it to the system's clip-board?

**Comment by ralphtheninja** [comment]
:+1:

**Comment by alessioalex** [comment]
that would be total awesomeness

**Comment by heapwolf** [comment]
@alessioalex what do you think of this? https://github.com/xavi-/node-copy-paste

**Comment by alessioalex** [comment]
Wow, hadn't seen that one. I knew of TJ's `cliparoo`, but it's old and unmaintained. This one seems nice and cross-OS.

Will look into it and try to implement it, see how it goes.

**Comment by alessioalex** [comment]
@hij1nx I can confirm that module not only works on Windows, but doesn't require all that fancy Visual Studio / .net bla bla tools (I have none installed). Greatness awaits :dancers:

**Comment by heapwolf** [comment]
this is working now, so im closing this.
